server:
  port: 8080

spring:
  application:
    name: websocket
  data:
    mongodb:
      username: username
      password: password
      host: localhost
      port: 27017
      database: chat_app
      authentication-database: admin